# -*- coding: utf-8 -*-
"""list_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lyZwTzwBiWOV0V80StNLuqIYVDTkKXCJ
"""

contoh1=[1,'dua',3,4.0,5]
print(contoh1)
print(contoh1[3])

contoh1=[1,'dua',3,'empat',5]
print(contoh1)
print(contoh1[3])