# -*- coding: utf-8 -*-
"""Variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17D-l6goHS8n0a3lqC-VjaEO2yUniftix
"""

bilangan1=20
bilangan2=10
pengurangan=bilangan1-bilangan2
print(pengurangan)